name: 'build-test'
on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: yarn package

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/checkout@v2
        with:
          ref: 'latest'
          path: 'dist'

      - run: yarn --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: yarn package
      - name: Setup git
        run: |
          git config --global user.name "FinbertMDS"
          git config --global user.email "ngovanhuy.cntt3@gmail.com"

          cat >$HOME/.netrc <<EOF
          machine github.com
          login FinbertMDS
          password ${GITHUB_TOKEN}
          EOF

      - name: Deploy to latest branch
        working-directory: ./dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Abort job successfully when no scripts updated
          test -z "$(git status --short)" && exit 0

          git add .
          git commit --message "Release for ${GITHUB_SHA}"
          git push origin latest
          
  test-latest:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: Hello world action step
        id: hello
        uses: FinbertMDS/hello-world-javascript-action@latest
        with:
          who-to-greet: 'FinbertMDS'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"